### ISSUE TITLE
[GUI] Logout button glitches

### ISSUE THREAD

**Issue by realKarthikNair** [AroraKaran19/NSUT-hack#1]
Steps to repro

- Click on the menu button 
- Logout button doesn't appear
- But it appears when hovered upon the same (menu) icon

Expected output

- Click on the menu button
- Logout button appears

Python Version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Affected part: GUI/tkinter

Please fix ASAP

**Comment by AroraKaran19** [comment]
Thank you for bringing the issue regarding the logout button in the GUI/tkinter to our attention. We sincerely appreciate your effort in providing us with the detailed steps to reproduce the problem and the expected output. As the owner of the application, we take user feedback seriously and are committed to delivering a smooth and seamless user experience.

**Comment by realKarthikNair** [comment]
Thank you @AroraKaran19 🎉
